version: "3.8"
 
services:
  app:
    image: ${IMAGE_NAME} # Apenas usa a imagem, não constrói
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    working_dir: /var/www
    depends_on:
      - mysql
    env_file:
      - .env
 
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
 
volumes:
  mysql_data: